### ISSUE TITLE
Immagine non corrispondente alla descrizione

### ISSUE THREAD

**Issue by esplo78** [MicrosoftDocs/powerbi-docs.it-it#2]
L'ultima immagine di esempio non corrisponde a quanto scritto subito sopra.
"La tabella di esempio seguente presenta la formattazione URL Web applicata alla colonna Stato, Barre dei dati condizionali e la Formattazione di sfondo applicata alla colonna Affordability."

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Formattazione della tabella condizionale in Power BI Desktop - Power BI](https://docs.microsoft.com/it-it/power-bi/desktop-conditional-table-formatting#feedback)
* Content Source: [powerbi-docs/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs.it-it/blob/live/powerbi-docs/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @esplo78
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Grazie per i commenti e i suggerimenti inviati.   

Il team tecnico ha esaminato e accettato i tuoi suggerimenti. I suggerimenti sono stati implementati e pubblicati negli articoli aggiornati sul sito Docs nelle pagine seguenti https://docs.microsoft.com/it-it/power-bi/desktop-conditional-table-formatting#feedback.   

Il tuo contributo ai nostri articoli è molto apprezzato e ci auguriamo che vorrai continuare a inviarci i tuoi utili suggerimenti.  

Cordiali saluti,  
Il team internazionale Microsoft Docs
